// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7dBdh3V3TYm2CPUfjW5h77mxOHZ3iWMk',
    appId: '1:430264974266:web:262108cb2c8ab7590cbb83',
    messagingSenderId: '430264974266',
    projectId: 'mukkuri-6c30e',
    authDomain: 'mukkuri-6c30e.firebaseapp.com',
    storageBucket: 'mukkuri-6c30e.appspot.com',
    measurementId: 'G-C7KRPSLC3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR68J651HXV2bWL-n8xUl3LAM_070Mym8',
    appId: '1:430264974266:android:19e551b17b7c669a0cbb83',
    messagingSenderId: '430264974266',
    projectId: 'mukkuri-6c30e',
    storageBucket: 'mukkuri-6c30e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbfS0Rly7I-w_kJHW3Vdbr6D9d_HDDYU0',
    appId: '1:430264974266:ios:177e608e49cbfba60cbb83',
    messagingSenderId: '430264974266',
    projectId: 'mukkuri-6c30e',
    storageBucket: 'mukkuri-6c30e.appspot.com',
    iosBundleId: 'com.example.mukkuri',
  );
}